name: Obfuscate js code

on:
  push:
    branches:
      - main
    paths:
      - _worker.js
  workflow_dispatch:

jobs:
  obfuscate:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install javascript-obfuscator globally
        run: npm install -g javascript-obfuscator@4.1.1

      - name: Remove old obfuscated file if exists
        run: |
          if [ -f _worker_obfuscated.js ]; then
            rm _worker_obfuscated.js
            echo "Remove old _worker_obfuscated.js"
          fi

      - name: Obfuscate _worker.js
        run: |
          javascript-obfuscator _worker.js \
            --output _worker_obfuscated.js \
            --compact true \
            --control-flow-flattening true \
            --control-flow-flattening-threshold 0.8 \
            --dead-code-injection true \
            --dead-code-injection-threshold 0.5 \
            --identifier-names-generator hexadecimal \
            --rename-globals true \
            --string-array true \
            --string-array-encoding 'rc4' \
            --string-array-threshold 0.8 \
            --transform-object-keys true \
            --unicode-escape-sequence true

      - name: Commit changes if any
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add _worker_obfuscated.js
          if git diff --cached --quiet; then
            echo "No file is changed, skip commit"
          else
            git commit -m "Generate new _worker_obfuscated.js"
          fi

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.PAT }}
          branch: ${{ github.ref }}