name: Upstream Sync

permissions:
  contents: write

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  sync_latest_from_upstream:
    name: Sync _worker.js and README.md from upstream repo
    runs-on: ubuntu-latest
    if: ${{ github.event.repository.fork }}

    steps:
      - name: Checkout target repo
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            _worker.js
            README.md

      - name: Set up git user
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Add upstream remote
        run: git remote add upstream https://github.com/cmliu/edgetunnel.git

      - name: Fetch upstream
        run: git fetch upstream main

      - name: Sync _worker.js and README.md from upstream
        run: |
          git checkout upstream/main -- _worker.js README.md
          git add _worker.js README.md
          git commit -m "Sync _worker.js and README.md from upstream" || echo "No changes to commit"

      - name: Push changes
        run: git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}